### ISSUE TITLE
Implement Error Codes & Response Statuses

### ISSUE THREAD

**Issue by bhennes2** [LaunchPadLab/rails_util#8]
Try to [match](http://jsonapi.org/format/#document-top-level).

**Comment by rkillackey** [comment]
@dianacamacho Do you have some time early next week to meet about this? I think we're implementing most already, but we should look into how we're structuring associations...would be a breaking change I think

**Comment by dianacamacho** [comment]
@rkillackey yup. free whenever!

**Comment by rkillackey** [comment]
@bhennes2 Are there any current issues with error responses that you've noticed? Diana and I think we're pretty close to matching the documents linked above. I believe this issue was opened before we made updates to JsonHelper to match the Json API specs, so I just want to make sure it's still relevant!

**Comment by bhennes2** [comment]
Yeah I don't recall anything off the top of my head. If this issue is nothing more than verifying we are following the correct standards, that works for me!
